SCBiblioteca/SCBiblioteca/Models/Compra.cs
namespace SCBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Compra
    {
        public int IdCompra { get; set; }

        [Display(Name = "Correlativo")]
        public string Correlativo { get; set; }

        [Required(ErrorMessage = "La {0} es requerida.")]
        public int Cantidad { get; set; }

        [Required(ErrorMessage = "El {0} es requerido.")]
        public decimal Subtotal { get; set; }
        public Nullable<decimal> TotalCompra { get; set; }

        [Display(Name = "Fecha")]
        [Required(ErrorMessage = "La {0} es requerida.")]
        public System.DateTime FechaCompra { get; set; }

        [Display(Name = "Libro")]
        public int IdLibro { get; set; }

        [Display(Name = "Editorial")]
        public int IdEditorial { get; set; }
        public virtual Editorial Editorial { get; set; }
        public virtual Libro Libro { get; set; }
    }
}

SCBiblioteca/SCBiblioteca/Controllers/ComprasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using SCBiblioteca.Models;

namespace SCBiblioteca.Controllers
{
    public class ComprasController : Controller
    {
        private SCBibliotecaEntities db = new SCBibliotecaEntities();

        // GET: Compras
        public ActionResult Index()
        {
            var compra = db.Compra.Include(c => c.Editorial).Include(c => c.Libro);
            return View(compra.ToList());
        }

        // GET: Compras/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Compra compra = db.Compra.Find(id);
            if (compra == null)
            {
                return HttpNotFound();
            }
            return View(compra);
        }

        // GET: Compras/Create
        public ActionResult Create()
        {
            ViewBag.IdEditorial = new SelectList(db.Editorial, "IdEditorial", "Editorial1");
            ViewBag.IdLibro = new SelectList(db.Libro, "IdLibro", "Titulo");
            return View();
        }

        public ActionResult VerReporteCompra(string fecha)
        {
            string[] f = fecha.Split('-');
            string month = f[1];
            string year = f[0];
            var reporte = new ReportClass();
            reporte.FileName = Server.MapPath("/Reports/ReporteCompraFecha.rpt");
            //ESTABLECIENDO UN PARAMETRO AL REPORTE
            reporte.SetParameterValue("month", month);
            reporte.SetParameterValue("year", year);
            //conexion para el reporte
            var coninfo = new ConnectionInfo { ServerName = "DESKTOP-GN9NFD8", DatabaseName = "SCBiblioteca", IntegratedSecurity = true };
            TableLogOnInfo logoninfo = new TableLogOnInfo();
            Tables tables;
            tables = reporte.Database.Tables;
            foreach (Table item in tables)
            {
                logoninfo = item.LogOnInfo;
                logoninfo.ConnectionInfo = coninfo;
                item.ApplyLogOnInfo(logoninfo);
            }
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();
            Stream stream = reporte.ExportToStream(ExportFormatType.PortableDocFormat);
            return new FileStreamResult(stream, "application/pdf");
        }

        // POST: Compras/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdCompra,Correlativo,Cantidad,Subtotal,TotalCompra,FechaCompra,IdLibro,IdEditorial")] Compra compra)
        {
            ModelDB m = new ModelDB();
            if (ModelState.IsValid)
            {

                if (m.SumarStock(compra.Cantidad, compra.IdLibro))
                {
                    db.Compra.Add(compra);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(compra);
                }

            }

            ViewBag.IdEditorial = new SelectList(db.Editorial, "IdEditorial", "Editorial1", compra.IdEditorial);
            ViewBag.IdLibro = new SelectList(db.Libro, "IdLibro", "Titulo", compra.IdLibro);
            return View(compra);
        }

        // GET: Compras/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Compra compra = db.Compra.Find(id);
            if (compra == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdEditorial = new SelectList(db.Editorial, "IdEditorial", "Editorial1", compra.IdEditorial);
            ViewBag.IdLibro = new SelectList(db.Libro, "IdLibro", "Titulo", compra.IdLibro);
            return View(compra);
        }

        // POST: Compras/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdCompra,Correlativo,Cantidad,Subtotal,TotalCompra,FechaCompra,IdLibro,IdEditorial")] Compra compra)
        {
            ModelDB m = new ModelDB();
            if (ModelState.IsValid)
            {
                if (compra.Cantidad <= m.StockLibros(compra.IdLibro))
                {
                    if (m.RestarStock(m.CompraCantidad(compra.IdCompra), compra.IdLibro))
                    {
                        if (m.SumarStock(compra.Cantidad, compra.IdLibro))
                        {
                            db.Entry(compra).State = EntityState.Modified;
                            db.SaveChanges();
                            return RedirectToAction("Index");
                        }
                    }
                }
                else
                {
                    ViewBag.CantidadLibro = "La cantidad de libros debe ser menor";
                }

            }
            ViewBag.IdEditorial = new SelectList(db.Editorial, "IdEditorial", "Editorial1", compra.IdEditorial);
            ViewBag.IdLibro = new SelectList(db.Libro, "IdLibro", "Titulo", compra.IdLibro);
            return View(compra);
        }

        // GET: Compras/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Compra compra = db.Compra.Find(id);
            if (compra == null)
            {
                return HttpNotFound();
            }
            return View(compra);
        }

        // POST: Compras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Compra compra = db.Compra.Find(id);
            db.Compra.Remove(compra);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SCBiblioteca/SCBiblioteca/Views/Compras/Create.cshtml
@model SCBiblioteca.Models.Compra
@{
    String sesion = (String)(System.Web.HttpContext.Current.Session["UserSesion"]);
}
@if (@System.Web.HttpContext.Current.Session["UserSesion"] != null && sesion.Equals("Administrador"))
{
    ViewBag.Title = "Create";
    Random r = new Random();
    DateTime thisDay = DateTime.Now;
    string d = thisDay.Day.ToString();
    string m = thisDay.Month.ToString();
    string a = thisDay.Year.ToString();
    string h = thisDay.Hour.ToString();
    string mi = thisDay.Minute.ToString();
    string s = thisDay.Second.ToString();
    string ms = thisDay.Millisecond.ToString();
    string random = r.Next(1, 1000).ToString();
    string dd = thisDay.ToString("dddd");
    char ddf = dd.ToUpper().FirstOrDefault();
    string correlativo = "F" + ddf + d + m + a + "H" + h + mi + s + ms + "R-" + random;

    <div class="container my-5" style="padding:16px;">
        <h2>Agregar</h2>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Compra</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Correlativo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="text" value=@correlativo class="form-control" name="Correlativo" readonly />
                        @Html.ValidationMessageFor(model => model.Correlativo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Subtotal, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Subtotal, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Subtotal, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.FechaCompra, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="datetime-local" class="form-control" name="FechaCompra" />
                        @Html.ValidationMessageFor(model => model.FechaCompra, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IdLibro, "IdLibro", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("IdLibro", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IdLibro, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IdEditorial, "IdEditorial", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("IdEditorial", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IdEditorial, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Agregar" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Regresar a la lista", "Index")
        </div>
    </div>
}
else
{
    {
        ViewBag.Title = "NotFound";
    }
    @RenderPage("~/Views/Home/NotFound.cshtml");
}
<script src="~/Scripts/jquery-3.5.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SCBiblioteca/SCBiblioteca/Views/Compras/Delete.cshtml
@model SCBiblioteca.Models.Compra
@{
    String sesion = (String)(System.Web.HttpContext.Current.Session["UserSesion"]);
}
@if (@System.Web.HttpContext.Current.Session["UserSesion"] != null && sesion.Equals("Administrador"))
{
    {
        ViewBag.Title = "Delete";
    }

    <div class="container my-5" style="padding:16px;">
        <h2>Eliminar</h2>
        <div class="alert alert-danger" role="alert">
            <h3><strong>¿Está seguro que desea eliminar la Compra?</strong></h3>
            <p><strong>Nota: No debe eliminar la compra</strong></p>
        </div>
        <div>
            <h4>Compra</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Correlativo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Correlativo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Cantidad)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Cantidad)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Subtotal)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Subtotal)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TotalCompra)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TotalCompra)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.FechaCompra)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FechaCompra)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Editorial.Editorial1)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Editorial.Editorial1)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Libro.Titulo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Libro.Titulo)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>
    </div>
}
else
{
    {
        ViewBag.Title = "NotFound";
    }
    @RenderPage("~/Views/Home/NotFound.cshtml");
}

SCBiblioteca/SCBiblioteca/Views/Compras/Details.cshtml
@model SCBiblioteca.Models.Compra

@{
    String sesion = (String)(System.Web.HttpContext.Current.Session["UserSesion"]);
}

@if (@System.Web.HttpContext.Current.Session["UserSesion"] != null && sesion.Equals("Administrador"))
{
    {
        ViewBag.Title = "Details";
    }
    <div class="container my-5" style="padding:16px;">
        <h2>Detalles</h2>

        <div>
            <h4>Compra</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Correlativo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Correlativo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Cantidad)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Cantidad)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Subtotal)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Subtotal)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TotalCompra)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TotalCompra)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.FechaCompra)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FechaCompra)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Editorial.Editorial1)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Editorial.Editorial1)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Libro.Titulo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Libro.Titulo)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("Editar", "Edit", new { id = Model.IdCompra }) |
            @Html.ActionLink("Regresar a la lista", "Index")
        </p>
    </div>
}
else
{
    {
        ViewBag.Title = "NotFound";
    }
    @RenderPage("~/Views/Home/NotFound.cshtml");
}
<script src="~/Scripts/jquery-3.5.1.min.js"></script>

SCBiblioteca/SCBiblioteca/Views/Compras/Edit.cshtml
@model SCBiblioteca.Models.Compra

@{
    String sesion = (String)(System.Web.HttpContext.Current.Session["UserSesion"]);
}

@if (@System.Web.HttpContext.Current.Session["UserSesion"] != null && sesion.Equals("Administrador"))
{
    {
        ViewBag.Title = "Edit";
    }
    <div class="container my-5" style="padding:16px;">
        <h2>Editar</h2>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Compra</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IdCompra)

                <div class="form-group">
                    @Html.LabelFor(model => model.Correlativo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Correlativo, new { htmlAttributes = new { @class = "form-control-plaintext", @readonly = "true" } })
                        @Html.ValidationMessageFor(model => model.Correlativo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Cantidad, new
                        {
                            htmlAttributes = new { @class = "form-control" }
                })
                        @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Subtotal, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Subtotal, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Subtotal, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.FechaCompra, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FechaCompra, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FechaCompra, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IdLibro, "IdLibro", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("IdLibro", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IdLibro, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IdEditorial, "IdEditorial", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("IdEditorial", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IdEditorial, "", new { @class = "text-danger" })
                    </div>
                </div>
                <span style="color:red">@ViewBag.CantidadLibro</span>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Guardar" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Regresar a la lista", "Index")
        </div>
    </div>
}
else
{
    {
        ViewBag.Title = "NotFound";
    }
    @RenderPage("~/Views/Home/NotFound.cshtml");
}
<script src="~/Scripts/jquery-3.5.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SCBiblioteca/SCBiblioteca/Views/Compras/Index.cshtml
@model IEnumerable<SCBiblioteca.Models.Compra>

@{
    String sesion = (String)(System.Web.HttpContext.Current.Session["UserSesion"]);
}
@if (@System.Web.HttpContext.Current.Session["UserSesion"] != null && sesion.Equals("Administrador"))
{
    {
        ViewBag.Title = "Index";
    }
    <script>
        $(document).ready(function () {
            $.noConflict();
            var table = $('#tablacompras').dataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.16/i18n/Spanish.json"
                }
            });
        });
    </script>
    <div class="container my-5" style="padding:16px;">
        <h2>Compras</h2>

        <p>
            @Html.ActionLink("Agregar Nueva", "Create")
        </p>
        @using (Html.BeginForm("VerReporteCompra", "Compras", FormMethod.Get, htmlAttributes: new { id = "formcompras", target = "_blank" }))
        {
            <div class="form-group row border">
                <label for="top" class="col-sm-3 col-form-label">Reporte de Compras por mes y Año</label>
                <div class="col-sm-3">
                    <input type="month" class="form-control" name="fecha" required>
                </div>
                <button type="submit" class="col-sm-2 btn btn-primary">Generar</button>
            </div>
        }
        <table class="table table-bordered table-responsive-lg" id="tablacompras" width="100%">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Correlativo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Cantidad)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Subtotal)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TotalCompra)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FechaCompra)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Editorial.Editorial1)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Libro.Titulo)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Correlativo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cantidad)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Subtotal)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TotalCompra)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FechaCompra)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Editorial.Editorial1)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Libro.Titulo)
                        </td>
                        <td>
                            @Html.ActionLink("Editar", "Edit", new { id = item.IdCompra }, new { @class = "btn btn-success my-1" })
                            @Html.ActionLink("Detalles", "Details", new { id = item.IdCompra }, new { @class = "btn btn-info my-1" })
                            @Html.ActionLink("Eliminar", "Delete", new { id = item.IdCompra }, new { @class = "btn btn-danger my-1 disabled" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    {
        ViewBag.Title = "NotFound";
    }
    @RenderPage("~/Views/Home/NotFound.cshtml");
}
<script src="~/Scripts/jquery-3.5.1.min.js"></script>