SCBiblioteca/SCBiblioteca/Models/Solicitud.cs
namespace SCBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud()
        {
            this.Prestamo = new HashSet<Prestamo>();
        }

        public int IdSolicitud { get; set; }
        [Display(Name = "Fecha de la Solicitud")]
        [Required(ErrorMessage = "La {0} es requerida.")]
        public System.DateTime FechaSolicitud { get; set; }

        [Display(Name = "Cantidad de libros")]
        [Range(1, 3, ErrorMessage = "La {0} debe ser {1} o maximo {2}")]
        [Required(ErrorMessage = "La {0} es requerida.")]
        public int CantidadLibros { get; set; }
        public int Activo { get; set; }

        [Display(Name = "Cliente")]
        public Nullable<int> IdCliente { get; set; }

        [Display(Name = "Libro")]
        [Required(ErrorMessage = "El {0} es requerido.")]
        public int IdLibro { get; set; }

        [Display(Name = "Usuario")]
        public Nullable<int> IdUsuario { get; set; }

        public virtual Cliente Cliente { get; set; }
        public virtual Libro Libro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamo> Prestamo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}

SCBiblioteca/SCBiblioteca/Controllers/SolicitudesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using SCBiblioteca.Models;

namespace SCBiblioteca.Controllers
{
    public class SolicitudesController : Controller
    {
        private SCBibliotecaEntities db = new SCBibliotecaEntities();

        // GET: Solicitudes
        public ActionResult Index(string parametro)

        {
            var solicitud = db.Solicitud.Include(s => s.Cliente).Include(s => s.Libro).Include(s => s.Usuario);
            System.Web.HttpContext.Current.Session["ParametroReporteC"] = parametro;
            return View(solicitud.ToList());
        }

        public ActionResult MisSolicitudes()
        {
            var solicitud = db.Solicitud.Include(s => s.Cliente).Include(s => s.Libro).Include(s => s.Usuario);
            return View(solicitud.ToList());
        }


        public ActionResult VerComprobanteUsuario(string parametro)
        {
            var reporte = new ReportClass();
            reporte.FileName = Server.MapPath("/Reports/ComprobanteUsuario.rpt");
            //ESTABLECIENDO UN PARAMETRO AL REPORTE
            reporte.SetParameterValue("ComprobanteCod", parametro);
            //conexion para el reporte
            var coninfo = new ConnectionInfo { ServerName = "DESKTOP-GN9NFD8", DatabaseName = "SCBiblioteca", IntegratedSecurity = true };
            TableLogOnInfo logoninfo = new TableLogOnInfo();
            Tables tables;
            tables = reporte.Database.Tables;
            foreach (Table item in tables)
            {
                logoninfo = item.LogOnInfo;
                logoninfo.ConnectionInfo = coninfo;
                item.ApplyLogOnInfo(logoninfo);
            }
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();
            Stream stream = reporte.ExportToStream(ExportFormatType.PortableDocFormat);
            return new FileStreamResult(stream, "application/pdf");
        }

        public ActionResult ConsultarLibros(string es)
        {
            var libro = db.Libro.Include(l => l.Autor).Include(l => l.Categoria).Include(l => l.Especialidad);
            ViewBag.ES = es;
            return View(libro.ToList());
        }

        // GET: Solicitudes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Solicitud solicitud = db.Solicitud.Find(id);
            if (solicitud == null)
            {
                return HttpNotFound();
            }
            return View(solicitud);
        }

        // GET: Solicitudes/Create
        public ActionResult Create()
        {
            ViewBag.IdCliente = new SelectList(db.Cliente, "IdCliente", "NombreCompleto");
            ViewBag.IdLibro = new SelectList(db.Libro, "IdLibro", "Titulo");
            ViewBag.IdUsuario = new SelectList(db.Usuario, "IdUsuario", "NombreCompleto");
            return View();
        }

        // POST: Solicitudes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdSolicitud,FechaSolicitud,CantidadLibros,Activo,IdCliente,IdLibro,IdUsuario")] Solicitud solicitud)
        {
            if (ModelState.IsValid)
            {
                db.Solicitud.Add(solicitud);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdCliente = new SelectList(db.Cliente, "IdCliente", "NombreCompleto", solicitud.IdCliente);
            ViewBag.IdLibro = new SelectList(db.Libro, "IdLibro", "Titulo", solicitud.IdLibro);
            ViewBag.IdUsuario = new SelectList(db.Usuario, "IdUsuario", "NombreCompleto", solicitud.IdUsuario);
            return View(solicitud);
        }

        public ActionResult Solicitud(int? id)
        {
            ModelDB m = new ModelDB();
            ViewBag.TituloLibro = m.TituloLibro(id);
            System.Web.HttpContext.Current.Session["IdLibro"] = id;
            ViewBag.display = "none";
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Solicitud(Solicitud solicitud)
        {
            ViewBag.display = "none";
            int id = Convert.ToInt32(System.Web.HttpContext.Current.Session["IdLibro"]);
            DateTime thisDay = DateTime.Now;
            ModelDB m = new ModelDB();
            if (ModelState.IsValid)
            {
                if (m.CantidadLibrosU((int)solicitud.IdUsuario) != 3)
                {
                    if (m.StockLibros(solicitud.IdLibro) >= solicitud.CantidadLibros)
                    {
                        if (m.RestarStock(solicitud.CantidadLibros, solicitud.IdLibro))
                        {
                            solicitud.IdLibro = id;
                            solicitud.Activo = 1;
                            solicitud.FechaSolicitud = thisDay;
                            db.Solicitud.Add(solicitud);
                            db.SaveChanges();
                            ViewBag.EstadoSolicitud = "exito";
                            return RedirectToAction("ConsultarLibros", new { es = ViewBag.EstadoSolicitud });

                        }
                        else
                        {
                            return RedirectToAction("ConsultarLibros");
                        }


                    }
                    else
                    {
                        ViewBag.Solicitud = "No hay Suficientes Libros";
                        ViewBag.TituloLibro = m.TituloLibro(id);
                        ViewBag.display = "normal";
                        return View(solicitud);

                    }
                }
                else
                {
                    ViewBag.Solicitud = "Ya exedio el Maximo de Libros prestados";
                    ViewBag.TituloLibro = m.TituloLibro(id);
                    ViewBag.display = "normal";
                    return View(solicitud);
                }

            }
            else
            {
                ViewBag.Solicitud = "Solicitud no procesada, comuniquese con atencion al cliente";
                ViewBag.TituloLibro = m.TituloLibro(id);
                ViewBag.display = "normal";
                return View(solicitud);
            }
        }

        // GET: Solicitudes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Solicitud solicitud = db.Solicitud.Find(id);
            if (solicitud == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCliente = new SelectList(db.Cliente, "IdCliente", "NombreCompleto", solicitud.IdCliente);
            ViewBag.IdLibro = new SelectList(db.Libro, "IdLibro", "Titulo", solicitud.IdLibro);
            ViewBag.IdUsuario = new SelectList(db.Usuario, "IdUsuario", "NombreCompleto", solicitud.IdUsuario);
            return View(solicitud);
        }

        // POST: Solicitudes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdSolicitud,FechaSolicitud,CantidadLibros,Activo,IdCliente,IdLibro,IdUsuario")] Solicitud solicitud)
        {
            if (ModelState.IsValid)
            {
                db.Entry(solicitud).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdCliente = new SelectList(db.Cliente, "IdCliente", "NombreCompleto", solicitud.IdCliente);
            ViewBag.IdLibro = new SelectList(db.Libro, "IdLibro", "Titulo", solicitud.IdLibro);
            ViewBag.IdUsuario = new SelectList(db.Usuario, "IdUsuario", "NombreCompleto", solicitud.IdUsuario);
            return View(solicitud);
        }

        // GET: Solicitudes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Solicitud solicitud = db.Solicitud.Find(id);
            if (solicitud == null)
            {
                return HttpNotFound();
            }
            return View(solicitud);
        }

        // POST: Solicitudes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            string sesion = (string)(System.Web.HttpContext.Current.Session["UserSesion"]);
            ModelDB m = new ModelDB();
            Solicitud solicitud = db.Solicitud.Find(id);
            if (m.SumarStock(solicitud.CantidadLibros, solicitud.IdLibro))
            {
                db.Solicitud.Remove(solicitud);
                db.SaveChanges();

                if (sesion.Equals("Usuario"))
                {
                    return RedirectToAction("MisSolicitudes");
                }
                else
                {
                    return RedirectToAction("Index");
                }

            }
            else
            {
                if (sesion.Equals("Usuario"))
                {
                    return RedirectToAction("MisSolicitudes");
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SCBiblioteca/SCBiblioteca/Views/Solicitudes/ConsultarLibros.cshtml
@model IEnumerable<SCBiblioteca.Models.Libro>
@{
    ViewBag.Title = "ConsultarLibros";
    ViewBag.ConsultarLibros = "active";
    string ss = ViewBag.ES;
}

<script>
    $(document).ready(function () {
        $.noConflict();
        var table = $('#tablelibros').dataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.16/i18n/Spanish.json"
            }
        });
    });
    console.log("estado s: ",@ss);
</script>
<style>
    .disabled {
        color: currentColor;
        cursor: not-allowed;
        opacity: 0.5;
        text-decoration: none;
    }
</style>
<div class="container my-5" style="padding:16px;">
    <h2>Consultar Libros</h2>
    @if (ss == "exito")
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            Solicitud Realizada correctamente
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }


    <table class="display table table-bordered table-responsive-lg" id="tablelibros" width="100%">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Titulo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Stock)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Autor.Autor1)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Categoria.Categoria1)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Especialidad.Especialidad1)
                </th>
                @if (@System.Web.HttpContext.Current.Session["UserSesion"] != null)
                {
                    <th>Acción</th>
                }
            </tr>

        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                var activo = (@Html.DisplayFor(modelItem => item.Activo));
                if (activo.ToString() != "0")
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Titulo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Stock)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Autor.Autor1)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Categoria.Categoria1)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Especialidad.Especialidad1)
                        </td>
                        @if (@System.Web.HttpContext.Current.Session["UserSesion"] != null)
                        {
                            var stock = (@Html.DisplayFor(modelItem => item.Stock));
                            <td>
                                @if (stock.ToString() != "0")
                                {
                                    @Html.ActionLink("Solicitar", "Solicitud", "Solicitudes", new { id = item.IdLibro }, new { @class = "my-1 btn btn-success " })
                                }
                                else
                                {
                                    <div class="alert alert-info py-0" role="alert">
                                        <p class="text-center py-0 my-0">No Disponible</p>
                                    </div>
                                }

                            </td>
                        }

                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<script src="~/Scripts/jquery-3.5.1.min.js"></script>

SCBiblioteca/SCBiblioteca/Views/Solicitudes/Create.cshtml
@model SCBiblioteca.Models.Solicitud

@{
    String sesion = (String)(System.Web.HttpContext.Current.Session["UserSesion"]);
}

@if (@System.Web.HttpContext.Current.Session["UserSesion"] != null && (sesion.Equals("Administrador")))
{
    {
        ViewBag.Title = "Create";
    }
    <div class="container my-5" style="padding:16px;">
        <h2>Agregar</h2>
        <div class="alert alert-danger" role="alert">
            <h3><strong>No Agregar solicitudes!!</strong></h3>
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Solicitud</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.FechaSolicitud, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FechaSolicitud, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FechaSolicitud, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CantidadLibros, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CantidadLibros, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CantidadLibros, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Activo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IdCliente, "IdCliente", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("IdCliente", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IdCliente, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IdLibro, "IdLibro", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("IdLibro", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IdLibro, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IdUsuario, "IdUsuario", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("IdUsuario", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IdUsuario, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-primary" disabled />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Regresar a la lista", "Index")
        </div>
    </div>
}
else
{
    {
        ViewBag.Title = "NotFound";
    }
    @RenderPage("~/Views/Home/NotFound.cshtml");
}
<script src="~/Scripts/jquery-3.5.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SCBiblioteca/SCBiblioteca/Views/Solicitudes/Delete.cshtml
@model SCBiblioteca.Models.Solicitud

@if (@System.Web.HttpContext.Current.Session["UserSesion"] != null)
{
    ViewBag.Title = "Delete";
    String sesion = (String)(System.Web.HttpContext.Current.Session["UserSesion"]);

    <div class="container my-5" style="padding:16px;">
        <h2>Eliminar</h2>
        <div class="alert alert-danger" role="alert">
            <h3><strong>Está seguro que desea eliminar la Solicitud?</strong></h3>
        </div>
        <div>
            <h4>Solicitud</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.FechaSolicitud)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FechaSolicitud)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CantidadLibros)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CantidadLibros)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Libro.Titulo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Libro.Titulo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Usuario.NombreCompleto)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Usuario.NombreCompleto)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @if (sesion.Equals("Bibliotecario") || sesion.Equals("Administrador"))
                    {
                        @Html.ActionLink("Regresar a la lista", "Index")
                    }
                    else
                    {
                        @Html.ActionLink("Regresar a mis solicitudes", "MisSolicitudes")
                    }

                </div>
            }
        </div>
    </div>
}
else
{
    {
        ViewBag.Title = "NotFound";
    }
    @RenderPage("~/Views/Home/NotFound.cshtml");
}

SCBiblioteca/SCBiblioteca/Views/Solicitudes/Details.cshtml
@model SCBiblioteca.Models.Solicitud

@{
    String sesion = (String)(System.Web.HttpContext.Current.Session["UserSesion"]);
}

@if (@System.Web.HttpContext.Current.Session["UserSesion"] != null && sesion.Equals("Administrador"))
{
    {
        ViewBag.Title = "Details";
    }
    <div class="container my-5" style="padding:16px;">
        <h2>Detalles</h2>

        <div>
            <h4>Solicitud</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.FechaSolicitud)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FechaSolicitud)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CantidadLibros)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CantidadLibros)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Activo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Activo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Cliente.NombreCompleto)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Cliente.NombreCompleto)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Libro.Titulo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Libro.Titulo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Usuario.NombreCompleto)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Usuario.NombreCompleto)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("Editar", "Edit", new { id = Model.IdSolicitud }) |
            @Html.ActionLink("Regresar a la lista", "Index")
        </p>
    </div>
}
else
{
    {
        ViewBag.Title = "NotFound";
    }
    @RenderPage("~/Views/Home/NotFound.cshtml");
}
<script src="~/Scripts/jquery-3.5.1.min.js"></script>

SCBiblioteca/SCBiblioteca/Views/Solicitudes/Index.cshtml
@model IEnumerable<SCBiblioteca.Models.Solicitud>

@{
    String sesion = (String)(System.Web.HttpContext.Current.Session["UserSesion"]);
}

@if (@System.Web.HttpContext.Current.Session["UserSesion"] != null && (sesion.Equals("Administrador") || sesion.Equals("Bibliotecario")))
{
    ViewBag.Title = "Index";
    ViewBag.PrestamosM = "active";
    ViewBag.Solicitudes = "active";
    String p = (String)(System.Web.HttpContext.Current.Session["ParametroReporteC"]);

    <script>
        $(document).ready(function () {
            $.noConflict();
            var table = $('#tablasolicitudes').dataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.16/i18n/Spanish.json"
                }
            });
        });
    </script>
    <div class="container my-5" style="padding:16px;">
        <h2>Solicitudes</h2>
        @if (p != null)
        {
            @Html.ActionLink("Generar Comprobante " + p, "VerComprobanteUsuario", "Solicitudes", new { parametro = p }, new { @class = "my-1 p-2 btn btn-primary ", target = "_blank" })
        }

        <table class="display table table-bordered table-responsive-lg" id="tablasolicitudes" width="100%">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.FechaSolicitud)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CantidadLibros)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Libro.Titulo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Usuario.NombreCompleto)
                    </th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    if ((@Html.DisplayFor(modelItem => item.Activo)).ToString() == "1")
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.FechaSolicitud)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CantidadLibros)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Libro.Titulo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Usuario.NombreCompleto)
                            </td>
                            <td>
                                @if (sesion.Equals("Administrador"))
                                {
                                    @Html.ActionLink("Editar", "Edit", new { id = item.IdSolicitud }, new { @class = "my-1 p-2 btn btn-success" });
                                    @Html.ActionLink("Detalles", "Details", new { id = item.IdSolicitud }, new { @class = "my-1 p-2 btn btn-warning" });

                                }
                                @if (sesion.Equals("Administrador") || sesion.Equals("Bibliotecario"))
                                {
                                    @Html.ActionLink("Eliminar", "Delete", new { id = item.IdSolicitud }, new { @class = "my-1 p-2 btn btn-danger" })
                                    @Html.ActionLink("Prestar", "Create", "Prestamos", new { idSolicitud = item.IdSolicitud }, new { @class = "my-1 p-2 btn btn-success " })

                                }
                            </td>
                        </tr>
                    }

                }
            </tbody>
        </table>
    </div>
}
else
{
    {
        ViewBag.Title = "NotFound";
    }
    @RenderPage("~/Views/Home/NotFound.cshtml");
}
<script src="~/Scripts/jquery-3.5.1.min.js"></script>

SCBiblioteca/SCBiblioteca/Views/Solicitudes/Solicitud.cshtml
@{

    String sesion = (String)(System.Web.HttpContext.Current.Session["UserSesion"]);
}
@if (@System.Web.HttpContext.Current.Session["UserSesion"] != null && sesion.Equals("Usuario"))
{
    ViewBag.Title = "Solicitud";
    int UserId = Convert.ToInt32(System.Web.HttpContext.Current.Session["UserId"]);
    int ClienteId = Convert.ToInt32(System.Web.HttpContext.Current.Session["ClienteId"]);
    int idLibro = Convert.ToInt32(System.Web.HttpContext.Current.Session["IdLibro"]);
    <div class="container my-5" style="padding:16px">
        <h2>Solicitud</h2>

        @using (Html.BeginForm("Solicitud", "Solicitudes", FormMethod.Post, htmlAttributes: new { id = "formSolicitud" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <div class="alert alert-info col-md-offset-2 col-md-10 py-0" role="alert">
                    <h3 class="py-0 my-0">@ViewBag.TituloLibro</h3>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Cantidad de Libros<span class="text-danger">*</span></label>
                    <div class="col-md-10">
                        <input type="number" min="1" max="3" class="form-control" name="CantidadLibros" value="1" />
                        <span style="color:red"><strong>NOTA: </strong>La Cantidad <strong>Maxima</strong> de Libros que Puede Prestar es <strong>3</strong></span>
                    </div>
                </div>

                <input type="hidden" value=@ClienteId name="IdCliente" />

                <input type="hidden" value=@idLibro name="IdLibro" />
                <input type="hidden" value=@UserId name="IdUsuario" />
                <div class="col-md-offset-2 col-md-10 py-2">
                    <p style="color:red">@ViewBag.Solicitud</p>
                    <a href='@Url.Action("ConsultarLibros", "Solicitudes")' style="display:@ViewBag.display">Regresar a Consultar Libros</a>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Solicitar" class="btn btn-primary" />
                    </div>
                </div>
            </div>
            <div>
                @Html.ActionLink("Regresar a la lista", "ConsultarLibros")
            </div>
        }
    </div>
}
else
{
    {
        ViewBag.Title = "NotFound";
    }
    @RenderPage("~/Views/Home/NotFound.cshtml");
}
<script src="~/Scripts/jquery-3.5.1.min.js"></script>